### STEP 1-- DATASET CREATION

In [1]:
import numpy as np

In [13]:
stds = np.array([
    [85, 90, 78, 92, 88],
    [70, 68, 75, 72, 74],
    [95, 98, 100, 96, 99],
    [60, 65, 58, 62, 64],
    [80, 82, 84, 79, 81]
])

print("the students and their marks as follows: \n", stds)

the students and their marks as follows: 
 [[ 85  90  78  92  88]
 [ 70  68  75  72  74]
 [ 95  98 100  96  99]
 [ 60  65  58  62  64]
 [ 80  82  84  79  81]]


### STEP 2--AVERAGE MARKS PER STUDENT

In [14]:
avg=np.mean(stds, axis=1)
print("average per student: \n", avg)

average per student: 
 [86.6 71.8 97.6 61.8 81.2]


### STEP 3-- HIGHEST AND LOWEST MARKS

In [ ]:
mini=np.min(stds, axis=1)
print("the minimum marks per student are as follows: \n", mini)

maxi=np.max(stds, axis=1)
print("the maximum marks per student are as follows: \n", maxi)

the minimum marks per student are as follows: 
 58
the maximum marks per student are as follows: 
 100


### STEP 4 --STANDARD DEVIATION PER STUDENT

In [16]:
std=np.std(stds, axis=1)

print("the standard deviation per student are as follows: \n", std)

the standard deviation per student are as follows: 
 [4.88262225 2.56124969 1.8547237  2.56124969 1.72046505]


### STEP 5 -- RANKING STUDENT

In [23]:
total=sum(stds)
print(total)

print(np.sort(total))

[390 403 395 401 406]
[390 395 401 403 406]


### STEP 6 -- TOP STUDENTS (CLASS AVERAGE)

In [26]:
clsavg=np.mean(stds)
print(clsavg)

print("students above class average are \n", np.where(total > clsavg))

79.8
students above class average are 
 (array([0, 1, 2, 3, 4]),)


### STEP 7 -- SUBJECT WISE ANALYSIS

In [28]:
print("subject wise analysis: -", np.mean(stds, axis=0))

print("highest marks in each subject: \n", np.max(stds, axis=0))
print("lowest marks in each subject: \n", np.min(stds, axis=0))

subject wise analysis: - [78.  80.6 79.  80.2 81.2]
highest marks in each subject: 
 [ 95  98 100  96  99]
lowest marks in each subject: 
 [60 65 58 62 64]


### STEP 8 PERCENTAGE CALC

In [30]:
per = (total / 500) * 100

print("Percentage")
print(per)

Percentage
[78.  80.6 79.  80.2 81.2]


### STEP 9 -- VISULAISATION READY DATA