## BASICS + INTRODUCTION

### How to import NumPy

In [1]:
import numpy as np

#### This widespread convention allows access to NumPy features with a short, recognizable prefix (np.) while distinguishing NumPy features from others that have the same name.

### Array fundamentals

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

####  Like the original list, the array is mutable.

In [3]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

#### One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [4]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

#### Two- and higher-dimensional arrays can be initialized from nested Python sequences:

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])