In [6]:
import numpy as np
a=np.array([1, 2, 3, 4, 5])
b=np.array([10, 20, 30, 40, 50])

print(a+b)

#since the size of the elements are same therefore sum is coming individually element wise


[11 22 33 44 55]


Why don't they concatenate?

Because NumPy is designed for mathematical and scientific computing. So operators like +, -, *, / are defined as mathematical operations.

In [2]:
# however if it is different size then cocatenation would happen

a=np.array([1, 2, 3, 4])
b=np.array([11, 12, 13, 14, 15])

print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [17]:
# but in case of python list
a1=[12, 13, 14]
b1=[1, 2, 3]
b2=a1[:2]
print(b1)
print(a1+b1)
print(b2)
b2[0]=9999
print(b2)
print(b1)

[1, 2, 3]
[12, 13, 14, 1, 2, 3]
[12, 13]
[9999, 13]
[1, 2, 3]


In [7]:
# we can use other operators also with same size arrays

print(a>b)
print(a<b)
print(a==b)
print(a!=b)

[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [9]:
#we can also use this way

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.power(a, b))
print(np.mod(a, b))
print(np.divide(a, b))
print(np.abs(np.array([-1, -2, -2])))

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[                   1              1048576      205891132094649
                    0 -6776596920136667815]
[1 2 3 4 5]
[0.1 0.1 0.1 0.1 0.1]
[1 2 2]


In [ ]:
# VERY IMPORTANT CONCEPTS
print(a)
c=a[3:]
print(c)
c[0]=45
print(c)
print(a)

[ 1  2  3 90  5]
[90  5]
[45  5]
[ 1  2  3 45  5]


## FANCY INDEXING