# MATHEMATICAL FUNCTIONS

In [1]:
#check the directory we can use it with any packages
import numpy as np
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [ ]:
a=np.array([1, 2, 3, 4, 5])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.(a))
print(np.(a))

## 1. Arithmetic Functions

In [3]:
a = np.array([1, 2, 3, 4])

print(np.add(a, 5))
print(np.subtract(a, 1))
print(np.multiply(a, 2))
print(np.divide(a, 2))
print(np.power(a, 2))
print(np.mod(a, 2))

[6 7 8 9]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1 0 1 0]


## 2. Exponential and Logarithmic Functions

In [4]:
a = np.array([1, 2, 3])

print(np.exp(a))      # e^x
print(np.log(a))      # Natural log
print(np.log10(a))    # Base-10 log
print(np.log2(a))     # Base-2 log

[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]


## 3. Square Root and Powers

In [5]:
a = np.array([1, 4, 9, 16])

print(np.sqrt(a))
print(np.square(a))
print(np.cbrt(a))

[1. 2. 3. 4.]
[  1  16  81 256]
[1.         1.58740105 2.08008382 2.5198421 ]


## 4. Trigonometric Functions

In [6]:
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))
print(np.tan(angles))

print(np.arcsin([0, 1]))
print(np.arccos([1, 0]))
print(np.arctan([0, 1]))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0.         1.57079633]
[0.         1.57079633]
[0.         0.78539816]


## 5. Rounding Functions

In [7]:
a = np.array([2.3, 2.7, -2.3, -2.7])

print(np.floor(a))
print(np.ceil(a))
print(np.round(a))
print(np.trunc(a))

[ 2.  2. -3. -3.]
[ 3.  3. -2. -2.]
[ 2.  3. -2. -3.]
[ 2.  2. -2. -2.]


## 6. Absolute Value

In [8]:
a = np.array([-3, -2, 5])

print(np.abs(a))

[3 2 5]


## 7. Statistical Functions

In [9]:
a = np.array([2, 4, 6, 8, 10])

print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))

30
6.0
6.0
2
10
2.8284271247461903
8.0


## 8. Cumulative Functions

In [10]:
a = np.array([1, 2, 3, 4])

print(np.cumsum(a))
print(np.cumprod(a))

[ 1  3  6 10]
[ 1  2  6 24]


## 9. Comparison Functions

In [11]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print(np.maximum(a, b))
print(np.minimum(a, b))

[3 2 3]
[1 2 1]


## 10. Sign Functions

In [12]:
a = np.array([-5, 0, 8])

print(np.sign(a))

[-1  0  1]


## 11. Clipping Values

In [13]:
a = np.array([1, 5, 10, 15])

print(np.clip(a, 3, 12))

[ 3  5 10 12]


## 12. Linear Algebra Functions

In [14]:
A = np.array([[1, 2], [3, 4]])

print(np.linalg.det(A))
print(np.linalg.inv(A))
print(np.linalg.eig(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


## 13. Common Constants

In [15]:
print(np.pi)
print(np.e)
print(np.inf)
print(np.nan)

3.141592653589793
2.718281828459045
inf
nan
